export const REQUEST_COMPARE_PRODUCTS = 'REQUEST_COMPARE_PRODUCTS';
export const RECEIVED_COMPARE_PRODUCTS = 'RECEIVED_COMPARE_PRODUCTS';
export const FAILED_RECEIVEING_COMPARE_PRODUCTS = 'FAILED_RECEIVEING_COMPARE_PRODUCTS';
export const RESET_COMPARE_PRODUCTS = 'RESET_COMPARE_PRODUCTS';
export const DISPLAY_ALERT = 'DISPLAY_ALERT';
